### ISSUE TITLE
custom subdomain http request does not load nor redirects to https site

### ISSUE THREAD

**Issue by gerardcl** [fermyon/feedback#29] opened 2023-08-19 07:07 UTC
**Describe the bug**
I did deploy with success a spin app in fermyon cloud, now I am using a subdomain within a fermyon app and it did work great, the problem is when I access it via http:// scheme it does not redirect to https:// scheme,  it does work though when using the given fermyon domain for that app.

**Frequency of the bug**
Please check one:
- [x] Consistent repro
- [ ] Intermittent repro
- [ ] No repro

**Set-up information**
spin 1.4.1 (e0bd911 2023-07-12)

**To Reproduce**
1. Go to 'http://mysubdomain.mydomain.com' (with  or without `/` at the end) 
2. Does not load, it times out connection to https://mysubdomain.mydomain.com:1443
3. Go to 'https://mysubdomain.mydomain.com' (with  or without `/` at the end) 
4. Does work

**Expected behavior**
To have an automated redirect to https:// scheme at is happens with the given fermyon domain for the same app.

**Screenshots**
N/A

**Additional context**
Questions: is it a known issue? is there a well known solution? shall I implement an http listener and do a redirect on my own? thanks!

**Comment by mikkelhegn** [comment] 2023-08-21 09:36
Hi @gerardcl

I'm not able to reproduce this error. Could I ask you to send an e-mail to support@fermyon.com with details about the app (the domain name should be included). That way we can look in to the specifics for that application.

Thanks, Mikkel

**Comment by radu-matei** [comment] 2023-08-21 11:44
I'm seeing the same behavior as reported in the issue, @mikkelhegn .
We are looking into this and hope to update the issue soon.

Thanks for reportin!

**Comment by mikkelhegn** [comment] 2023-08-21 12:11
+1 on this behavior using curl to follow the redirect `curl -iL http://name.mydomain.com`

My browser (Arc) handles the redirects correctly.

@gerardcl Can you confirm that in step 2 - you meant to say `https` and not `http`?

> To Reproduce
> Steps to reproduce the behavior:
> 1. Go to 'http://mysubdomain.mydomain.com/' (with or without / at the end)
> 2. Does not load, it times out connection to http://mysubdomain.mydomain.com:1443/
> 3. Go to 'https://mysubdomain.mydomain.com/' (with or without / at the end)
> Does work

**Comment by gerardcl** [comment] 2023-08-21 21:59
> +1 on this behavior using curl to follow the redirect `curl -iL http://name.mydomain.com`
> 
> My browser (Arc) handles the redirects correctly.
> 
> @gerardcl Can you confirm that in step 2 - you meant to say `https` and not `http`?
> 
> > To Reproduce
> > Steps to reproduce the behavior:
> > 
> > 1. Go to 'http://mysubdomain.mydomain.com/' (with or without / at the end)
> > 2. Does not load, it times out connection to http://mysubdomain.mydomain.com:1443/
> > 3. Go to 'https://mysubdomain.mydomain.com/' (with or without / at the end)
> >    Does work

Hi @mikkelhegn! You're right, I've just edited the description accordingly. Thanks 👍

**Comment by ingride** [comment] 2023-08-24 15:44
hey there, thank you for reporting this issue! It was caused by a misconfiguration on our end which we now fixed. 
Great find and we appreciate your time! 

-Ingrid

**Closed as completed by ingride** 2023-08-24 15:44 UTC
Labels: bug, investigating
