### ISSUE TITLE
Discord invitation expired

### ISSUE THREAD

**Issue by upachler** [fermyon/feedback#17] opened 2023-04-08 15:28 UTC
Hello, it appears that the discord invitation link shown on various spots in the website has expired - also on the feedback page:
https://github.com/fermyon/feedback (see page bottom).

**Comment by flynnduism** [comment] 2023-04-08 20:40
Thanks for reporting @upachler 

Double checking our server invites - indeed we have a few different ones being linked to in different scenarios. The one you reference - https://discord.com/invite/AAFNfS7NGf  _should_ still be working (there is no expiration), we're looking into the issue

**Comment by upachler** [comment] 2023-04-12 19:45
Hi, was just checking again; this is what I see when I open the page (partial screenshot showing the localized message). It says: 'Invitation Invalid - This invitation is either expired, or you do not have permission to enter'):

<img width="518" alt="Bildschirmfoto 2023-04-12 um 21 42 07" src="https://user-images.githubusercontent.com/15084162/231567404-229ece9b-7186-476d-934c-4a6527b52185.png">

**Comment by flynnduism** [comment] 2023-04-18 22:00
@upachler huh

What's your discord username, I can invite you directly that way

**Comment by mikkelhegn** [comment] 2023-05-15 09:49
Closing as we cannot reproduce (just tried again today). Please let us know if you still haven't been able to join the Discord server.

**Closed as completed by mikkelhegn** 2023-05-15 09:49 UTC
